-- xjg-api base schema
-- Character set: utf8mb4
-- Storage engine: InnoDB
-- Note: Foreign keys are intentionally not enforced in phase 1 migration
-- to keep legacy JSON import tolerant.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_uid VARCHAR(64) NOT NULL,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(64) NOT NULL,
      role VARCHAR(32) NOT NULL DEFAULT 'employee',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  department VARCHAR(64) NOT NULL DEFAULT '项目管理',
  department_en VARCHAR(128) NOT NULL DEFAULT 'PROJECT MANAGEMENT',
  job VARCHAR(64) NOT NULL DEFAULT '项目专员',
  mbti VARCHAR(16) NOT NULL DEFAULT 'ENTP',
  mood VARCHAR(255) NOT NULL DEFAULT '',
  signature VARCHAR(255) NOT NULL DEFAULT '',
  profile_note VARCHAR(255) NOT NULL DEFAULT '',
  character_label VARCHAR(64) NOT NULL DEFAULT '',
  avatar_image LONGTEXT NULL,
  character_image LONGTEXT NULL,
  signature_image LONGTEXT NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_user_uid (user_uid),
  UNIQUE KEY uniq_users_username (username),
  KEY idx_users_email (email),
  KEY idx_users_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_states (
  id VARCHAR(64) NOT NULL,
  data_json LONGTEXT NOT NULL,
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS departments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  department_uid VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  name_en VARCHAR(128) NOT NULL DEFAULT '',
  parent_department_uid VARCHAR(64) NOT NULL DEFAULT '',
  manager_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_departments_department_uid (department_uid),
  UNIQUE KEY uniq_departments_name (name),
  KEY idx_departments_parent_uid (parent_department_uid),
  KEY idx_departments_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  role_key VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT '',
  is_system TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_roles_role_key (role_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  permission_key VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_permissions_permission_key (permission_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  role_key VARCHAR(64) NOT NULL,
  permission_key VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_role_permissions_role_permission (role_key, permission_key),
  KEY idx_role_permissions_role_key (role_key),
  KEY idx_role_permissions_permission_key (permission_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_uid VARCHAR(64) NOT NULL,
  role_key VARCHAR(64) NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT 'global',
  scope_uid VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_roles_user_role_scope (user_uid, role_key, scope_type, scope_uid),
  KEY idx_user_roles_user_uid (user_uid),
  KEY idx_user_roles_role_key (role_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  suffix VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_groups_group_uid (group_uid),
  KEY idx_project_groups_title (title),
  KEY idx_project_groups_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_uid VARCHAR(64) NOT NULL,
  legacy_project_id BIGINT NULL,
  group_uid VARCHAR(64) NOT NULL DEFAULT '',
  name VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  owner_text VARCHAR(255) NOT NULL DEFAULT '',
  start_date DATE NULL,
  end_date DATE NULL,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_projects_project_uid (project_uid),
  KEY idx_projects_group_uid (group_uid),
  KEY idx_projects_status_sort (status, sort_order),
  KEY idx_projects_legacy_project_id (legacy_project_id),
  KEY idx_projects_name (name),
  KEY idx_projects_archived (archived)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  member_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  member_name VARCHAR(64) NOT NULL DEFAULT '',
  member_role VARCHAR(32) NOT NULL DEFAULT 'readonly',
  department VARCHAR(64) NOT NULL DEFAULT '',
  department_en VARCHAR(128) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  joined_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_members_member_uid (member_uid),
  UNIQUE KEY uniq_project_members_project_user_name (project_uid, user_uid, member_name),
  KEY idx_project_members_project_uid (project_uid),
  KEY idx_project_members_user_uid (user_uid),
  KEY idx_project_members_role (member_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  legacy_task_id BIGINT NULL,
  title VARCHAR(255) NOT NULL,
  task_type VARCHAR(64) NOT NULL DEFAULT '',
  module_key VARCHAR(32) NOT NULL DEFAULT 'project',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  owner_text VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'todo',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  start_date DATE NULL,
  end_date DATE NULL,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  expanded TINYINT(1) NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_tasks_task_uid (task_uid),
  KEY idx_tasks_project_uid (project_uid),
  KEY idx_tasks_legacy_task_id (legacy_task_id),
  KEY idx_tasks_project_status (project_uid, status),
  KEY idx_tasks_module_key (module_key),
  KEY idx_tasks_owner_user_uid (owner_user_uid),
  KEY idx_tasks_archived (archived),
  KEY idx_tasks_start_end (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_comments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  comment_uid VARCHAR(64) NOT NULL,
  task_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  user_name VARCHAR(64) NOT NULL DEFAULT '',
  user_dept VARCHAR(128) NOT NULL DEFAULT '',
  tone VARCHAR(32) NOT NULL DEFAULT '',
  content_text TEXT NOT NULL,
  commented_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_task_comments_comment_uid (comment_uid),
  KEY idx_task_comments_task_uid (task_uid),
  KEY idx_task_comments_project_uid (project_uid),
  KEY idx_task_comments_user_uid (user_uid),
  KEY idx_task_comments_task_time (task_uid, commented_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  active_project_uid VARCHAR(64) GENERATED ALWAYS AS (
    CASE WHEN status = 'active' THEN project_uid ELSE NULL END
  ) STORED,
  title VARCHAR(255) NOT NULL DEFAULT '项目排期',
  start_date DATE NULL,
  end_date DATE NULL,
  default_view VARCHAR(32) NOT NULL DEFAULT 'timeline',
  view_config_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_plans_plan_uid (plan_uid),
  UNIQUE KEY uniq_schedule_plans_active_project_uid (active_project_uid),
  KEY idx_schedule_plans_project_status (project_uid, status),
  KEY idx_schedule_plans_project_uid (project_uid),
  KEY idx_schedule_plans_start_end (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  task_uid VARCHAR(64) NULL,
  legacy_task_id BIGINT NULL,
  item_type VARCHAR(32) NOT NULL DEFAULT 'schedule',
  title VARCHAR(255) NOT NULL,
  module_key VARCHAR(32) NOT NULL DEFAULT 'project',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  owner_text VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'todo',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  progress INT NOT NULL DEFAULT 0,
  start_date DATE NULL,
  end_date DATE NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  hidden TINYINT(1) NOT NULL DEFAULT 0,
  link_task TINYINT(1) NOT NULL DEFAULT 0,
  link_flow TINYINT(1) NOT NULL DEFAULT 0,
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_items_item_uid (item_uid),
  KEY idx_schedule_items_plan_sort (plan_uid, sort_order),
  KEY idx_schedule_items_project_uid (project_uid),
  KEY idx_schedule_items_task_uid (task_uid),
  KEY idx_schedule_items_start_end (start_date, end_date),
  KEY idx_schedule_items_type_status (item_type, status),
  KEY idx_schedule_items_module_key (module_key),
  KEY idx_schedule_items_hidden (hidden)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_dependencies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dependency_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  from_item_uid VARCHAR(64) NOT NULL,
  to_item_uid VARCHAR(64) NOT NULL,
  dependency_type VARCHAR(32) NOT NULL DEFAULT 'finish_to_start',
  lag_days INT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_dependencies_uid (dependency_uid),
  UNIQUE KEY uniq_schedule_dependencies_edge (from_item_uid, to_item_uid, dependency_type),
  KEY idx_schedule_dependencies_plan_uid (plan_uid),
  KEY idx_schedule_dependencies_from_item_uid (from_item_uid),
  KEY idx_schedule_dependencies_to_item_uid (to_item_uid),
  KEY idx_schedule_dependencies_project_uid (project_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  snapshot_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary_json LONGTEXT NULL,
  snapshot_json LONGTEXT NOT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  created_by_name VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_snapshots_uid (snapshot_uid),
  KEY idx_schedule_snapshots_plan_created_at (plan_uid, created_at),
  KEY idx_schedule_snapshots_project_created_at (project_uid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  item_count INT NOT NULL DEFAULT 0,
  template_json LONGTEXT NOT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_templates_uid (template_uid),
  KEY idx_schedule_templates_owner_user_uid (owner_user_uid),
  KEY idx_schedule_templates_visibility (visibility),
  KEY idx_schedule_templates_title (title)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_template_shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_uid VARCHAR(64) NOT NULL,
  template_uid VARCHAR(64) NOT NULL,
  from_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  to_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  permission VARCHAR(16) NOT NULL DEFAULT 'read',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  note VARCHAR(255) NOT NULL DEFAULT '',
  shared_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_template_shares_uid (share_uid),
  UNIQUE KEY uniq_schedule_template_shares_template_target (template_uid, to_user_uid),
  KEY idx_schedule_template_shares_template_uid (template_uid),
  KEY idx_schedule_template_shares_from_user_uid (from_user_uid),
  KEY idx_schedule_template_shares_to_user_uid (to_user_uid),
  KEY idx_schedule_template_shares_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_item_comments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  comment_uid VARCHAR(64) NOT NULL,
  item_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  user_name VARCHAR(64) NOT NULL DEFAULT '',
  user_dept VARCHAR(128) NOT NULL DEFAULT '',
  tone VARCHAR(32) NOT NULL DEFAULT '',
  content_text TEXT NOT NULL,
  commented_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_item_comments_uid (comment_uid),
  KEY idx_schedule_item_comments_item_uid (item_uid),
  KEY idx_schedule_item_comments_project_uid (project_uid),
  KEY idx_schedule_item_comments_user_uid (user_uid),
  KEY idx_schedule_item_comments_item_commented_at (item_uid, commented_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comment_mentions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  mention_uid VARCHAR(64) NOT NULL,
  comment_uid VARCHAR(64) NOT NULL,
  task_uid VARCHAR(64) NOT NULL DEFAULT '',
  mentioned_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  mentioned_username VARCHAR(64) NOT NULL DEFAULT '',
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_comment_mentions_mention_uid (mention_uid),
  KEY idx_comment_mentions_comment_uid (comment_uid),
  KEY idx_comment_mentions_task_uid (task_uid),
  KEY idx_comment_mentions_user_read (mentioned_user_uid, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notification_uid VARCHAR(64) NOT NULL,
  recipient_user_uid VARCHAR(64) NOT NULL,
  type VARCHAR(64) NOT NULL DEFAULT 'general',
  title VARCHAR(255) NOT NULL DEFAULT '',
  content_text TEXT NULL,
  resource_type VARCHAR(64) NOT NULL DEFAULT '',
  resource_uid VARCHAR(64) NOT NULL DEFAULT '',
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  task_uid VARCHAR(64) NOT NULL DEFAULT '',
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  actor_name VARCHAR(128) NOT NULL DEFAULT '',
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  read_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_notifications_notification_uid (notification_uid),
  KEY idx_notifications_recipient_read_created (recipient_user_uid, is_read, created_at),
  KEY idx_notifications_project_uid (project_uid),
  KEY idx_notifications_task_uid (task_uid),
  KEY idx_notifications_resource (resource_type, resource_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tag_uid VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  color VARCHAR(32) NOT NULL DEFAULT '',
  scope VARCHAR(32) NOT NULL DEFAULT 'workspace',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_system TINYINT(1) NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_tags_tag_uid (tag_uid),
  UNIQUE KEY uniq_tags_scope_name (scope, name),
  KEY idx_tags_color (color),
  KEY idx_tags_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_uid VARCHAR(64) NOT NULL,
  tag_uid VARCHAR(64) NOT NULL DEFAULT '',
  tag_name VARCHAR(64) NOT NULL DEFAULT '',
  tag_color VARCHAR(32) NOT NULL DEFAULT '',
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_tags_project_tag (project_uid, tag_uid, tag_name),
  KEY idx_project_tags_project_uid (project_uid),
  KEY idx_project_tags_tag_uid (tag_uid),
  KEY idx_project_tags_tag_name (tag_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_uid VARCHAR(64) NOT NULL,
  legacy_template_id VARCHAR(64) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL,
  group_key VARCHAR(64) NOT NULL DEFAULT '',
  parent_template_uid VARCHAR(64) NOT NULL DEFAULT '',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  is_locked TINYINT(1) NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  task_count INT NOT NULL DEFAULT 0,
  content_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_templates_template_uid (template_uid),
  KEY idx_templates_legacy_template_id (legacy_template_id),
  KEY idx_templates_group_key (group_key),
  KEY idx_templates_parent_template_uid (parent_template_uid),
  KEY idx_templates_owner_user_uid (owner_user_uid),
  KEY idx_templates_visibility_sort (visibility, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS template_shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_uid VARCHAR(64) NOT NULL,
  template_uid VARCHAR(64) NOT NULL,
  from_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  to_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  permission VARCHAR(16) NOT NULL DEFAULT 'read',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  note VARCHAR(255) NOT NULL DEFAULT '',
  shared_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_template_shares_share_uid (share_uid),
  UNIQUE KEY uniq_template_shares_template_target (template_uid, to_user_uid),
  KEY idx_template_shares_template_uid (template_uid),
  KEY idx_template_shares_from_user_uid (from_user_uid),
  KEY idx_template_shares_to_user_uid (to_user_uid),
  KEY idx_template_shares_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS address_book (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  contact_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  username VARCHAR(64) NOT NULL DEFAULT '',
  display_name VARCHAR(128) NOT NULL,
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  job VARCHAR(128) NOT NULL DEFAULT '',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_address_book_contact_uid (contact_uid),
  UNIQUE KEY uniq_address_book_user_uid (user_uid),
  KEY idx_address_book_department_uid (department_uid),
  KEY idx_address_book_username (username),
  KEY idx_address_book_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  contact_uid VARCHAR(64) NOT NULL,
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  target_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  display_name VARCHAR(128) NOT NULL DEFAULT '',
  relation_type VARCHAR(32) NOT NULL DEFAULT 'coworker',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_contacts_contact_uid (contact_uid),
  UNIQUE KEY uniq_contacts_owner_target (owner_user_uid, target_user_uid),
  KEY idx_contacts_owner_user_uid (owner_user_uid),
  KEY idx_contacts_target_user_uid (target_user_uid),
  KEY idx_contacts_owner_relation_status (owner_user_uid, relation_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_uid VARCHAR(64) NOT NULL,
  resource_type VARCHAR(32) NOT NULL,
  resource_uid VARCHAR(64) NOT NULL,
  from_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  to_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  permission VARCHAR(16) NOT NULL DEFAULT 'read',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  shared_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_shares_share_uid (share_uid),
  KEY idx_shares_resource (resource_type, resource_uid),
  KEY idx_shares_to_user_uid (to_user_uid),
  KEY idx_shares_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS boards (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  board_uid VARCHAR(64) NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT 'project',
  scope_uid VARCHAR(64) NOT NULL DEFAULT '',
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL,
  description_text TEXT NULL,
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  is_archived TINYINT(1) NOT NULL DEFAULT 0,
  latest_version INT UNSIGNED NOT NULL DEFAULT 0,
  board_state_json LONGTEXT NULL,
  files_json LONGTEXT NULL,
  app_state_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_boards_board_uid (board_uid),
  KEY idx_boards_scope (scope_type, scope_uid),
  KEY idx_boards_project_uid (project_uid),
  KEY idx_boards_owner_user_uid (owner_user_uid),
  KEY idx_boards_archived_updated_at (is_archived, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS board_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  board_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  member_role VARCHAR(32) NOT NULL DEFAULT 'viewer',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_board_members_board_user (board_uid, user_uid),
  KEY idx_board_members_board_uid (board_uid),
  KEY idx_board_members_user_uid (user_uid),
  KEY idx_board_members_role (member_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS board_shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_uid VARCHAR(64) NOT NULL,
  board_uid VARCHAR(64) NOT NULL,
  from_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  to_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  permission VARCHAR(16) NOT NULL DEFAULT 'read',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  shared_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_board_shares_share_uid (share_uid),
  KEY idx_board_shares_board_uid (board_uid),
  KEY idx_board_shares_to_user_uid (to_user_uid),
  KEY idx_board_shares_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS board_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  history_uid VARCHAR(64) NOT NULL,
  board_uid VARCHAR(64) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  action_type VARCHAR(32) NOT NULL DEFAULT 'save',
  change_summary VARCHAR(255) NOT NULL DEFAULT '',
  elements_json LONGTEXT NULL,
  files_json LONGTEXT NULL,
  app_state_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_board_history_history_uid (history_uid),
  UNIQUE KEY uniq_board_history_board_version (board_uid, version_no),
  KEY idx_board_history_board_uid_created_at (board_uid, created_at),
  KEY idx_board_history_actor_user_uid (actor_user_uid),
  KEY idx_board_history_action_type (action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS board_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  snapshot_uid VARCHAR(64) NOT NULL,
  board_uid VARCHAR(64) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  snapshot_json LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_board_snapshots_snapshot_uid (snapshot_uid),
  UNIQUE KEY uniq_board_snapshots_board_version (board_uid, version_no),
  KEY idx_board_snapshots_board_uid_created_at (board_uid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS carousel_notices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notice_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content_text TEXT NOT NULL,
  notice_type VARCHAR(64) NOT NULL DEFAULT '',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  priority INT NOT NULL DEFAULT 0,
  link_text VARCHAR(80) NOT NULL DEFAULT '',
  link_url VARCHAR(512) NOT NULL DEFAULT '',
  link_target VARCHAR(16) NOT NULL DEFAULT '_self',
  start_at DATETIME NULL,
  end_at DATETIME NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_carousel_notices_notice_uid (notice_uid),
  KEY idx_carousel_notices_enabled_sort (enabled, sort_order),
  KEY idx_carousel_notices_active_status (enabled, status, priority, sort_order),
  KEY idx_carousel_notices_notice_type (notice_type),
  KEY idx_carousel_notices_active_window (start_at, end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_system_configs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  config_key VARCHAR(128) NOT NULL,
  config_value LONGTEXT NOT NULL,
  value_type VARCHAR(32) NOT NULL DEFAULT 'string',
  description VARCHAR(255) NOT NULL DEFAULT '',
  is_editable TINYINT(1) NOT NULL DEFAULT 1,
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_system_configs_key (config_key),
  KEY idx_admin_system_configs_editable (is_editable, config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  log_uid VARCHAR(64) NOT NULL,
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  actor_name VARCHAR(128) NOT NULL DEFAULT '',
  actor_role VARCHAR(32) NOT NULL DEFAULT '',
  action VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_uid VARCHAR(128) NOT NULL DEFAULT '',
  resource_name VARCHAR(255) NOT NULL DEFAULT '',
  ip_address VARCHAR(64) NOT NULL DEFAULT '',
  user_agent VARCHAR(512) NOT NULL DEFAULT '',
  summary VARCHAR(500) NOT NULL DEFAULT '',
  before_json LONGTEXT NULL,
  after_json LONGTEXT NULL,
  metadata_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_audit_logs_uid (log_uid),
  KEY idx_admin_audit_logs_actor_created (actor_user_uid, created_at),
  KEY idx_admin_audit_logs_resource (resource_type, resource_uid),
  KEY idx_admin_audit_logs_action_created (action, created_at),
  KEY idx_admin_audit_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_archives (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  archive_uid VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_uid VARCHAR(128) NOT NULL,
  resource_name VARCHAR(255) NOT NULL DEFAULT '',
  source_table VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'archived',
  archived_by VARCHAR(64) NOT NULL DEFAULT '',
  archived_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  restored_by VARCHAR(64) NOT NULL DEFAULT '',
  restored_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_archives_uid (archive_uid),
  UNIQUE KEY uniq_admin_archives_resource (resource_type, resource_uid),
  KEY idx_admin_archives_status_archived (status, archived_at),
  KEY idx_admin_archives_resource_type (resource_type),
  KEY idx_admin_archives_archived_by (archived_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_positions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  position_uid VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  level_name VARCHAR(64) NOT NULL DEFAULT '',
  description TEXT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_positions_uid (position_uid),
  KEY idx_hr_positions_department (department_uid, status),
  KEY idx_hr_positions_title (title),
  KEY idx_hr_positions_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_employee_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  employee_no VARCHAR(64) NOT NULL DEFAULT '',
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  position_uid VARCHAR(64) NOT NULL DEFAULT '',
  direct_manager_uid VARCHAR(64) NOT NULL DEFAULT '',
  hire_date DATE NULL,
  employment_type VARCHAR(32) NOT NULL DEFAULT 'full_time',
  employment_status VARCHAR(32) NOT NULL DEFAULT 'active',
  work_location VARCHAR(128) NOT NULL DEFAULT '',
  skills_json LONGTEXT NULL,
  emergency_contact_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_employee_profiles_uid (profile_uid),
  UNIQUE KEY uniq_hr_employee_profiles_user_uid (user_uid),
  KEY idx_hr_employee_profiles_employee_no (employee_no),
  KEY idx_hr_employee_profiles_department (department_uid, employment_status),
  KEY idx_hr_employee_profiles_position (position_uid),
  KEY idx_hr_employee_profiles_manager (direct_manager_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_attendance_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  attendance_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  work_date DATE NOT NULL,
  check_in_at DATETIME NULL,
  check_out_at DATETIME NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'present',
  hours DECIMAL(6,2) NOT NULL DEFAULT 0,
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_attendance_records_uid (attendance_uid),
  UNIQUE KEY uniq_hr_attendance_user_date (user_uid, work_date),
  KEY idx_hr_attendance_date_status (work_date, status),
  KEY idx_hr_attendance_user (user_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_leave_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  leave_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  leave_type VARCHAR(32) NOT NULL DEFAULT 'annual',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  days DECIMAL(6,2) NOT NULL DEFAULT 1,
  reason_text TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  approver_uid VARCHAR(64) NOT NULL DEFAULT '',
  approved_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_leave_requests_uid (leave_uid),
  KEY idx_hr_leave_user_status (user_uid, status),
  KEY idx_hr_leave_range (start_date, end_date),
  KEY idx_hr_leave_approver (approver_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_recruitment_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_uid VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  position_uid VARCHAR(64) NOT NULL DEFAULT '',
  headcount INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  opened_at DATE NULL,
  closed_at DATE NULL,
  description_text TEXT NULL,
  requirements_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_recruitment_jobs_uid (job_uid),
  KEY idx_hr_recruitment_jobs_department (department_uid, status),
  KEY idx_hr_recruitment_jobs_owner (owner_user_uid),
  KEY idx_hr_recruitment_jobs_status_priority (status, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_recruitment_candidates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  candidate_uid VARCHAR(64) NOT NULL,
  job_uid VARCHAR(64) NOT NULL DEFAULT '',
  name VARCHAR(128) NOT NULL,
  phone VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  stage VARCHAR(32) NOT NULL DEFAULT 'screening',
  source VARCHAR(64) NOT NULL DEFAULT '',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  expected_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  resume_url VARCHAR(512) NOT NULL DEFAULT '',
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_recruitment_candidates_uid (candidate_uid),
  KEY idx_hr_candidates_job_stage (job_uid, stage),
  KEY idx_hr_candidates_owner (owner_user_uid),
  KEY idx_hr_candidates_phone (phone),
  KEY idx_hr_candidates_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_performance_reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  review_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  period VARCHAR(32) NOT NULL,
  reviewer_uid VARCHAR(64) NOT NULL DEFAULT '',
  score DECIMAL(5,2) NOT NULL DEFAULT 0,
  grade VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  goals_json LONGTEXT NULL,
  comments_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_performance_reviews_uid (review_uid),
  UNIQUE KEY uniq_hr_performance_user_period (user_uid, period),
  KEY idx_hr_performance_reviewer (reviewer_uid),
  KEY idx_hr_performance_period_status (period, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_payroll_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payroll_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  payroll_month DATE NOT NULL,
  base_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  bonus DECIMAL(12,2) NOT NULL DEFAULT 0,
  deduction DECIMAL(12,2) NOT NULL DEFAULT 0,
  social_security DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_payroll_records_uid (payroll_uid),
  UNIQUE KEY uniq_hr_payroll_user_month (user_uid, payroll_month),
  KEY idx_hr_payroll_month_status (payroll_month, status),
  KEY idx_hr_payroll_user (user_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_assignment_previews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  preview_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  project_name VARCHAR(255) NOT NULL DEFAULT '',
  assignee_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  assignee_name VARCHAR(128) NOT NULL DEFAULT '',
  start_date DATE NULL,
  end_date DATE NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'preview',
  force_reason VARCHAR(255) NOT NULL DEFAULT '',
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_assignment_previews_uid (preview_uid),
  KEY idx_hr_assignment_assignee (assignee_user_uid, status),
  KEY idx_hr_assignment_project (project_uid),
  KEY idx_hr_assignment_range (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storage_files (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  storage_uid VARCHAR(64) NOT NULL,
  kind ENUM('image', 'video', 'chat_text', 'attachment') NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT '',
  scope_uid VARCHAR(128) NOT NULL DEFAULT '',
  conversation_uid VARCHAR(128) NOT NULL DEFAULT '',
  message_uid VARCHAR(128) NOT NULL DEFAULT '',
  original_name VARCHAR(255) NOT NULL DEFAULT '',
  safe_original_name VARCHAR(255) NOT NULL DEFAULT '',
  mime_type VARCHAR(128) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  checksum_sha256 CHAR(64) NOT NULL,
  relative_path VARCHAR(512) NOT NULL,
  metadata_json LONGTEXT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  uploaded_by VARCHAR(64) NOT NULL DEFAULT '',
  uploaded_by_name VARCHAR(128) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_storage_files_storage_uid (storage_uid),
  UNIQUE KEY uniq_storage_files_relative_path (relative_path),
  KEY idx_storage_files_kind_status_created (kind, status, created_at),
  KEY idx_storage_files_scope (scope_type, scope_uid, kind, status),
  KEY idx_storage_files_conversation (conversation_uid, message_uid),
  KEY idx_storage_files_uploaded_by (uploaded_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

