CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notification_uid VARCHAR(64) NOT NULL,
  recipient_user_uid VARCHAR(64) NOT NULL,
  type VARCHAR(64) NOT NULL DEFAULT 'general',
  title VARCHAR(255) NOT NULL DEFAULT '',
  content_text TEXT NULL,
  resource_type VARCHAR(64) NOT NULL DEFAULT '',
  resource_uid VARCHAR(64) NOT NULL DEFAULT '',
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  task_uid VARCHAR(64) NOT NULL DEFAULT '',
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  actor_name VARCHAR(128) NOT NULL DEFAULT '',
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  read_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_notifications_notification_uid (notification_uid),
  KEY idx_notifications_recipient_read_created (recipient_user_uid, is_read, created_at),
  KEY idx_notifications_project_uid (project_uid),
  KEY idx_notifications_task_uid (task_uid),
  KEY idx_notifications_resource (resource_type, resource_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
