-- Admin, HR, storage, and audit tables for first production launch.
-- This migration is additive and repeatable: CREATE TABLE IF NOT EXISTS only.
-- Foreign keys are intentionally not enforced in this phase; *_uid relation
-- columns are indexed and the application layer keeps legacy JSON imports tolerant.

CREATE TABLE IF NOT EXISTS admin_system_configs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  config_key VARCHAR(128) NOT NULL,
  config_value LONGTEXT NOT NULL,
  value_type VARCHAR(32) NOT NULL DEFAULT 'string',
  description VARCHAR(255) NOT NULL DEFAULT '',
  is_editable TINYINT(1) NOT NULL DEFAULT 1,
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_system_configs_key (config_key),
  KEY idx_admin_system_configs_editable (is_editable, config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  log_uid VARCHAR(64) NOT NULL,
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  actor_name VARCHAR(128) NOT NULL DEFAULT '',
  actor_role VARCHAR(32) NOT NULL DEFAULT '',
  action VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_uid VARCHAR(128) NOT NULL DEFAULT '',
  resource_name VARCHAR(255) NOT NULL DEFAULT '',
  ip_address VARCHAR(64) NOT NULL DEFAULT '',
  user_agent VARCHAR(512) NOT NULL DEFAULT '',
  summary VARCHAR(500) NOT NULL DEFAULT '',
  before_json LONGTEXT NULL,
  after_json LONGTEXT NULL,
  metadata_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_audit_logs_uid (log_uid),
  KEY idx_admin_audit_logs_actor_created (actor_user_uid, created_at),
  KEY idx_admin_audit_logs_resource (resource_type, resource_uid),
  KEY idx_admin_audit_logs_action_created (action, created_at),
  KEY idx_admin_audit_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_archives (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  archive_uid VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_uid VARCHAR(128) NOT NULL,
  resource_name VARCHAR(255) NOT NULL DEFAULT '',
  source_table VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'archived',
  archived_by VARCHAR(64) NOT NULL DEFAULT '',
  archived_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  restored_by VARCHAR(64) NOT NULL DEFAULT '',
  restored_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_archives_uid (archive_uid),
  UNIQUE KEY uniq_admin_archives_resource (resource_type, resource_uid),
  KEY idx_admin_archives_status_archived (status, archived_at),
  KEY idx_admin_archives_resource_type (resource_type),
  KEY idx_admin_archives_archived_by (archived_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_positions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  position_uid VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  level_name VARCHAR(64) NOT NULL DEFAULT '',
  description TEXT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_positions_uid (position_uid),
  KEY idx_hr_positions_department (department_uid, status),
  KEY idx_hr_positions_title (title),
  KEY idx_hr_positions_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_employee_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  employee_no VARCHAR(64) NOT NULL DEFAULT '',
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  position_uid VARCHAR(64) NOT NULL DEFAULT '',
  direct_manager_uid VARCHAR(64) NOT NULL DEFAULT '',
  hire_date DATE NULL,
  employment_type VARCHAR(32) NOT NULL DEFAULT 'full_time',
  employment_status VARCHAR(32) NOT NULL DEFAULT 'active',
  work_location VARCHAR(128) NOT NULL DEFAULT '',
  skills_json LONGTEXT NULL,
  emergency_contact_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_employee_profiles_uid (profile_uid),
  UNIQUE KEY uniq_hr_employee_profiles_user_uid (user_uid),
  KEY idx_hr_employee_profiles_employee_no (employee_no),
  KEY idx_hr_employee_profiles_department (department_uid, employment_status),
  KEY idx_hr_employee_profiles_position (position_uid),
  KEY idx_hr_employee_profiles_manager (direct_manager_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_attendance_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  attendance_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  work_date DATE NOT NULL,
  check_in_at DATETIME NULL,
  check_out_at DATETIME NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'present',
  hours DECIMAL(6,2) NOT NULL DEFAULT 0,
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_attendance_records_uid (attendance_uid),
  UNIQUE KEY uniq_hr_attendance_user_date (user_uid, work_date),
  KEY idx_hr_attendance_date_status (work_date, status),
  KEY idx_hr_attendance_user (user_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_leave_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  leave_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  leave_type VARCHAR(32) NOT NULL DEFAULT 'annual',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  days DECIMAL(6,2) NOT NULL DEFAULT 1,
  reason_text TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  approver_uid VARCHAR(64) NOT NULL DEFAULT '',
  approved_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_leave_requests_uid (leave_uid),
  KEY idx_hr_leave_user_status (user_uid, status),
  KEY idx_hr_leave_range (start_date, end_date),
  KEY idx_hr_leave_approver (approver_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_recruitment_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_uid VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  department_uid VARCHAR(64) NOT NULL DEFAULT '',
  department_name VARCHAR(128) NOT NULL DEFAULT '',
  position_uid VARCHAR(64) NOT NULL DEFAULT '',
  headcount INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  opened_at DATE NULL,
  closed_at DATE NULL,
  description_text TEXT NULL,
  requirements_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_recruitment_jobs_uid (job_uid),
  KEY idx_hr_recruitment_jobs_department (department_uid, status),
  KEY idx_hr_recruitment_jobs_owner (owner_user_uid),
  KEY idx_hr_recruitment_jobs_status_priority (status, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_recruitment_candidates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  candidate_uid VARCHAR(64) NOT NULL,
  job_uid VARCHAR(64) NOT NULL DEFAULT '',
  name VARCHAR(128) NOT NULL,
  phone VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  stage VARCHAR(32) NOT NULL DEFAULT 'screening',
  source VARCHAR(64) NOT NULL DEFAULT '',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  expected_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  resume_url VARCHAR(512) NOT NULL DEFAULT '',
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_recruitment_candidates_uid (candidate_uid),
  KEY idx_hr_candidates_job_stage (job_uid, stage),
  KEY idx_hr_candidates_owner (owner_user_uid),
  KEY idx_hr_candidates_phone (phone),
  KEY idx_hr_candidates_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_performance_reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  review_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  period VARCHAR(32) NOT NULL,
  reviewer_uid VARCHAR(64) NOT NULL DEFAULT '',
  score DECIMAL(5,2) NOT NULL DEFAULT 0,
  grade VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  goals_json LONGTEXT NULL,
  comments_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_performance_reviews_uid (review_uid),
  UNIQUE KEY uniq_hr_performance_user_period (user_uid, period),
  KEY idx_hr_performance_reviewer (reviewer_uid),
  KEY idx_hr_performance_period_status (period, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_payroll_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payroll_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL,
  payroll_month DATE NOT NULL,
  base_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  bonus DECIMAL(12,2) NOT NULL DEFAULT 0,
  deduction DECIMAL(12,2) NOT NULL DEFAULT 0,
  social_security DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_payroll_records_uid (payroll_uid),
  UNIQUE KEY uniq_hr_payroll_user_month (user_uid, payroll_month),
  KEY idx_hr_payroll_month_status (payroll_month, status),
  KEY idx_hr_payroll_user (user_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hr_assignment_previews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  preview_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  project_name VARCHAR(255) NOT NULL DEFAULT '',
  assignee_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  assignee_name VARCHAR(128) NOT NULL DEFAULT '',
  start_date DATE NULL,
  end_date DATE NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'preview',
  force_reason VARCHAR(255) NOT NULL DEFAULT '',
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_hr_assignment_previews_uid (preview_uid),
  KEY idx_hr_assignment_assignee (assignee_user_uid, status),
  KEY idx_hr_assignment_project (project_uid),
  KEY idx_hr_assignment_range (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS storage_files (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  storage_uid VARCHAR(64) NOT NULL,
  kind ENUM('image', 'video', 'chat_text', 'attachment') NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT '',
  scope_uid VARCHAR(128) NOT NULL DEFAULT '',
  conversation_uid VARCHAR(128) NOT NULL DEFAULT '',
  message_uid VARCHAR(128) NOT NULL DEFAULT '',
  original_name VARCHAR(255) NOT NULL DEFAULT '',
  safe_original_name VARCHAR(255) NOT NULL DEFAULT '',
  mime_type VARCHAR(128) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  checksum_sha256 CHAR(64) NOT NULL,
  relative_path VARCHAR(512) NOT NULL,
  metadata_json LONGTEXT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  uploaded_by VARCHAR(64) NOT NULL DEFAULT '',
  uploaded_by_name VARCHAR(128) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_storage_files_storage_uid (storage_uid),
  UNIQUE KEY uniq_storage_files_relative_path (relative_path),
  KEY idx_storage_files_kind_status_created (kind, status, created_at),
  KEY idx_storage_files_scope (scope_type, scope_uid, kind, status),
  KEY idx_storage_files_conversation (conversation_uid, message_uid),
  KEY idx_storage_files_uploaded_by (uploaded_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
