CREATE TABLE IF NOT EXISTS schedule_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  active_project_uid VARCHAR(64) GENERATED ALWAYS AS (
    CASE WHEN status = 'active' THEN project_uid ELSE NULL END
  ) STORED,
  title VARCHAR(255) NOT NULL DEFAULT '项目排期',
  start_date DATE NULL,
  end_date DATE NULL,
  default_view VARCHAR(32) NOT NULL DEFAULT 'timeline',
  view_config_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_plans_plan_uid (plan_uid),
  UNIQUE KEY uniq_schedule_plans_active_project_uid (active_project_uid),
  KEY idx_schedule_plans_project_status (project_uid, status),
  KEY idx_schedule_plans_project_uid (project_uid),
  KEY idx_schedule_plans_start_end (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  task_uid VARCHAR(64) NULL,
  legacy_task_id BIGINT NULL,
  item_type VARCHAR(32) NOT NULL DEFAULT 'schedule',
  title VARCHAR(255) NOT NULL,
  module_key VARCHAR(32) NOT NULL DEFAULT 'project',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  owner_text VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'todo',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  progress INT NOT NULL DEFAULT 0,
  start_date DATE NULL,
  end_date DATE NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  hidden TINYINT(1) NOT NULL DEFAULT 0,
  link_task TINYINT(1) NOT NULL DEFAULT 0,
  link_flow TINYINT(1) NOT NULL DEFAULT 0,
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_items_item_uid (item_uid),
  KEY idx_schedule_items_plan_sort (plan_uid, sort_order),
  KEY idx_schedule_items_project_uid (project_uid),
  KEY idx_schedule_items_task_uid (task_uid),
  KEY idx_schedule_items_start_end (start_date, end_date),
  KEY idx_schedule_items_type_status (item_type, status),
  KEY idx_schedule_items_module_key (module_key),
  KEY idx_schedule_items_hidden (hidden)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_dependencies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  dependency_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  from_item_uid VARCHAR(64) NOT NULL,
  to_item_uid VARCHAR(64) NOT NULL,
  dependency_type VARCHAR(32) NOT NULL DEFAULT 'finish_to_start',
  lag_days INT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_dependencies_uid (dependency_uid),
  UNIQUE KEY uniq_schedule_dependencies_edge (from_item_uid, to_item_uid, dependency_type),
  KEY idx_schedule_dependencies_plan_uid (plan_uid),
  KEY idx_schedule_dependencies_from_item_uid (from_item_uid),
  KEY idx_schedule_dependencies_to_item_uid (to_item_uid),
  KEY idx_schedule_dependencies_project_uid (project_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  snapshot_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary_json LONGTEXT NULL,
  snapshot_json LONGTEXT NOT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  created_by_name VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_snapshots_uid (snapshot_uid),
  KEY idx_schedule_snapshots_plan_created_at (plan_uid, created_at),
  KEY idx_schedule_snapshots_project_created_at (project_uid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  item_count INT NOT NULL DEFAULT 0,
  template_json LONGTEXT NOT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_templates_uid (template_uid),
  KEY idx_schedule_templates_owner_user_uid (owner_user_uid),
  KEY idx_schedule_templates_visibility (visibility),
  KEY idx_schedule_templates_title (title)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_template_shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_uid VARCHAR(64) NOT NULL,
  template_uid VARCHAR(64) NOT NULL,
  from_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  to_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  permission VARCHAR(16) NOT NULL DEFAULT 'read',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  note VARCHAR(255) NOT NULL DEFAULT '',
  shared_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_template_shares_uid (share_uid),
  UNIQUE KEY uniq_schedule_template_shares_template_target (template_uid, to_user_uid),
  KEY idx_schedule_template_shares_template_uid (template_uid),
  KEY idx_schedule_template_shares_from_user_uid (from_user_uid),
  KEY idx_schedule_template_shares_to_user_uid (to_user_uid),
  KEY idx_schedule_template_shares_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_item_comments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  comment_uid VARCHAR(64) NOT NULL,
  item_uid VARCHAR(64) NOT NULL,
  plan_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  user_name VARCHAR(64) NOT NULL DEFAULT '',
  user_dept VARCHAR(128) NOT NULL DEFAULT '',
  tone VARCHAR(32) NOT NULL DEFAULT '',
  content_text TEXT NOT NULL,
  commented_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_schedule_item_comments_uid (comment_uid),
  KEY idx_schedule_item_comments_item_uid (item_uid),
  KEY idx_schedule_item_comments_project_uid (project_uid),
  KEY idx_schedule_item_comments_user_uid (user_uid),
  KEY idx_schedule_item_comments_item_commented_at (item_uid, commented_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
