-- xjg-api base schema
-- Character set: utf8mb4
-- Storage engine: InnoDB
-- Note: Foreign keys are intentionally not enforced in phase 1 migration
-- to keep legacy JSON import tolerant.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_uid VARCHAR(64) NOT NULL,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(64) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'user',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  email VARCHAR(128) NOT NULL DEFAULT '',
  department VARCHAR(64) NOT NULL DEFAULT '项目管理',
  department_en VARCHAR(128) NOT NULL DEFAULT 'PROJECT MANAGEMENT',
  job VARCHAR(64) NOT NULL DEFAULT '项目专员',
  mbti VARCHAR(16) NOT NULL DEFAULT 'ENTP',
  mood VARCHAR(255) NOT NULL DEFAULT '',
  signature VARCHAR(255) NOT NULL DEFAULT '',
  profile_note VARCHAR(255) NOT NULL DEFAULT '',
  character_label VARCHAR(64) NOT NULL DEFAULT '',
  avatar_image LONGTEXT NULL,
  character_image LONGTEXT NULL,
  signature_image LONGTEXT NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_user_uid (user_uid),
  UNIQUE KEY uniq_users_username (username),
  KEY idx_users_email (email),
  KEY idx_users_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_states (
  id VARCHAR(64) NOT NULL,
  data_json LONGTEXT NOT NULL,
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  suffix VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_groups_group_uid (group_uid),
  KEY idx_project_groups_title (title),
  KEY idx_project_groups_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_uid VARCHAR(64) NOT NULL,
  legacy_project_id BIGINT NULL,
  group_uid VARCHAR(64) NOT NULL DEFAULT '',
  name VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  owner_text VARCHAR(255) NOT NULL DEFAULT '',
  start_date DATE NULL,
  end_date DATE NULL,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_projects_project_uid (project_uid),
  KEY idx_projects_group_uid (group_uid),
  KEY idx_projects_status_sort (status, sort_order),
  KEY idx_projects_legacy_project_id (legacy_project_id),
  KEY idx_projects_name (name),
  KEY idx_projects_archived (archived)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  member_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  member_name VARCHAR(64) NOT NULL DEFAULT '',
  member_role VARCHAR(32) NOT NULL DEFAULT 'readonly',
  department VARCHAR(64) NOT NULL DEFAULT '',
  department_en VARCHAR(128) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  joined_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_members_member_uid (member_uid),
  UNIQUE KEY uniq_project_members_project_user_name (project_uid, user_uid, member_name),
  KEY idx_project_members_project_uid (project_uid),
  KEY idx_project_members_user_uid (user_uid),
  KEY idx_project_members_role (member_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL,
  legacy_task_id BIGINT NULL,
  title VARCHAR(255) NOT NULL,
  task_type VARCHAR(64) NOT NULL DEFAULT '',
  module_key VARCHAR(32) NOT NULL DEFAULT 'project',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  owner_text VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'todo',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  start_date DATE NULL,
  end_date DATE NULL,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  expanded TINYINT(1) NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  note_text TEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_tasks_task_uid (task_uid),
  KEY idx_tasks_project_uid (project_uid),
  KEY idx_tasks_legacy_task_id (legacy_task_id),
  KEY idx_tasks_project_status (project_uid, status),
  KEY idx_tasks_module_key (module_key),
  KEY idx_tasks_owner_user_uid (owner_user_uid),
  KEY idx_tasks_archived (archived),
  KEY idx_tasks_start_end (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_comments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  comment_uid VARCHAR(64) NOT NULL,
  task_uid VARCHAR(64) NOT NULL,
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  user_uid VARCHAR(64) NOT NULL DEFAULT '',
  user_name VARCHAR(64) NOT NULL DEFAULT '',
  user_dept VARCHAR(128) NOT NULL DEFAULT '',
  tone VARCHAR(32) NOT NULL DEFAULT '',
  content_text TEXT NOT NULL,
  commented_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_task_comments_comment_uid (comment_uid),
  KEY idx_task_comments_task_uid (task_uid),
  KEY idx_task_comments_project_uid (project_uid),
  KEY idx_task_comments_user_uid (user_uid),
  KEY idx_task_comments_task_time (task_uid, commented_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tag_uid VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  color VARCHAR(32) NOT NULL DEFAULT '',
  scope VARCHAR(32) NOT NULL DEFAULT 'workspace',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  sort_order BIGINT NOT NULL DEFAULT 0,
  is_system TINYINT(1) NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_tags_tag_uid (tag_uid),
  UNIQUE KEY uniq_tags_scope_name (scope, name),
  KEY idx_tags_color (color),
  KEY idx_tags_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_uid VARCHAR(64) NOT NULL,
  tag_uid VARCHAR(64) NOT NULL DEFAULT '',
  tag_name VARCHAR(64) NOT NULL DEFAULT '',
  tag_color VARCHAR(32) NOT NULL DEFAULT '',
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_project_tags_project_tag (project_uid, tag_uid, tag_name),
  KEY idx_project_tags_project_uid (project_uid),
  KEY idx_project_tags_tag_uid (tag_uid),
  KEY idx_project_tags_tag_name (tag_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_uid VARCHAR(64) NOT NULL,
  legacy_template_id VARCHAR(64) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL,
  group_key VARCHAR(64) NOT NULL DEFAULT '',
  parent_template_uid VARCHAR(64) NOT NULL DEFAULT '',
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  is_locked TINYINT(1) NOT NULL DEFAULT 0,
  sort_order BIGINT NOT NULL DEFAULT 0,
  task_count INT NOT NULL DEFAULT 0,
  content_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_templates_template_uid (template_uid),
  KEY idx_templates_legacy_template_id (legacy_template_id),
  KEY idx_templates_group_key (group_key),
  KEY idx_templates_parent_template_uid (parent_template_uid),
  KEY idx_templates_owner_user_uid (owner_user_uid),
  KEY idx_templates_visibility_sort (visibility, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS template_shares (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  share_uid VARCHAR(64) NOT NULL,
  template_uid VARCHAR(64) NOT NULL,
  from_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  to_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  permission VARCHAR(16) NOT NULL DEFAULT 'read',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  note VARCHAR(255) NOT NULL DEFAULT '',
  shared_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_template_shares_share_uid (share_uid),
  UNIQUE KEY uniq_template_shares_template_target (template_uid, to_user_uid),
  KEY idx_template_shares_template_uid (template_uid),
  KEY idx_template_shares_from_user_uid (from_user_uid),
  KEY idx_template_shares_to_user_uid (to_user_uid),
  KEY idx_template_shares_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS boards (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  board_uid VARCHAR(64) NOT NULL,
  scope_type VARCHAR(32) NOT NULL DEFAULT 'project',
  scope_uid VARCHAR(64) NOT NULL DEFAULT '',
  project_uid VARCHAR(64) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL,
  description_text TEXT NULL,
  owner_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  is_archived TINYINT(1) NOT NULL DEFAULT 0,
  latest_version INT UNSIGNED NOT NULL DEFAULT 0,
  board_state_json LONGTEXT NULL,
  files_json LONGTEXT NULL,
  app_state_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_boards_board_uid (board_uid),
  KEY idx_boards_scope (scope_type, scope_uid),
  KEY idx_boards_project_uid (project_uid),
  KEY idx_boards_owner_user_uid (owner_user_uid),
  KEY idx_boards_archived_updated_at (is_archived, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS board_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  history_uid VARCHAR(64) NOT NULL,
  board_uid VARCHAR(64) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  actor_user_uid VARCHAR(64) NOT NULL DEFAULT '',
  action_type VARCHAR(32) NOT NULL DEFAULT 'save',
  change_summary VARCHAR(255) NOT NULL DEFAULT '',
  elements_json LONGTEXT NULL,
  files_json LONGTEXT NULL,
  app_state_json LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_board_history_history_uid (history_uid),
  UNIQUE KEY uniq_board_history_board_version (board_uid, version_no),
  KEY idx_board_history_board_uid_created_at (board_uid, created_at),
  KEY idx_board_history_actor_user_uid (actor_user_uid),
  KEY idx_board_history_action_type (action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS carousel_notices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notice_uid VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content_text TEXT NOT NULL,
  notice_type VARCHAR(64) NOT NULL DEFAULT '',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  priority INT NOT NULL DEFAULT 0,
  link_text VARCHAR(80) NOT NULL DEFAULT '',
  link_url VARCHAR(512) NOT NULL DEFAULT '',
  link_target VARCHAR(16) NOT NULL DEFAULT '_self',
  start_at DATETIME NULL,
  end_at DATETIME NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  payload_json LONGTEXT NULL,
  created_by VARCHAR(64) NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_carousel_notices_notice_uid (notice_uid),
  KEY idx_carousel_notices_enabled_sort (enabled, sort_order),
  KEY idx_carousel_notices_active_status (enabled, status, priority, sort_order),
  KEY idx_carousel_notices_notice_type (notice_type),
  KEY idx_carousel_notices_active_window (start_at, end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

